BASE_TASK_CONFIG_PATH: habitat_extensions/config/robo_vlnce_task.yaml
SIMULATOR_GPU_ID: [0]
TORCH_GPU_ID: 0
NUM_PROCESSES: 1
TRAINER_NAME : "hierarchical_trainer"

TENSORBOARD_DIR: /home/mirshad7/data/robo-vln/tensorboard_dirs/hierarchical_s2s/run_2
CHECKPOINT_FOLDER: /home/mirshad7/data/robo-vln/checkpoints/hierarchical_s2s/run_2
EVAL_CKPT_PATH_DIR: /home/mirshad7/data/robo-vln/checkpoints/hierarchical_s2s/run_2/ckpt.45.pth

VIDEO_DIR: "/home/mirshad7/data/robo-vln/tensorboard_dirs/hierarchical_s2s/run_2/videos"
PLOT_ATTENTION: False
VIDEO_OPTION: ["disk"]  # options: "disk", "tensorboard"

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_seen
  EPISODE_COUNT: 100
  #576
  VAL_LOG_DIR : validation_logging/seq2seq_bert
DAGGER:
  ITERATIONS: 1
  EPOCHS: 45
  UPDATE_SIZE: 20
  BATCH_SIZE: 1
  P: 1.0
  PRELOAD_LMDB_FEATURES: True
  LMDB_FEATURES_DIR: /home/mirshad7/data/robo-vln/trajectory_dir/robo_complete/train/trajectories.lmdb
  LMDB_EVAL_DIR: /home/mirshad7/data/robo-vln/trajectory_dir/robo_complete/val_seen/trajectories.lmdb

MODEL:
  INSTRUCTION_ENCODER:
    final_state_only: True
    use_pretrained_embeddings: True
    is_bert: False
