BASE_TASK_CONFIG_PATH: habitat_extensions/config/robo_vlnce_task.yaml
SIMULATOR_GPU_ID: [0]
TORCH_GPU_ID: 0
NUM_PROCESSES: 5
TRAINER_NAME : "robo_vln_trainer"

TENSORBOARD_DIR: /srv/share/mirshad7/data/robo-vln/tensorboard_dirs/seq2seq_robo
CHECKPOINT_FOLDER: srv/share/mirshad7/data/robo-vln/checkpoints/seq2seq_robo
EVAL_CKPT_PATH_DIR: /srv/share/mirshad7/data/robo-vln/checkpoints/seq2seq_robo

VIDEO_DIR: "videos/debug/seq2seq_text_attn/test/seen"
PLOT_ATTENTION: True
VIDEO_OPTION: []  # options: "disk", "tensorboard"

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_seen
  EPISODE_COUNT: 778
  VAL_LOG_DIR : validation_logging/seq2seq_text_attn/test_run/seen
DAGGER:
  ITERATIONS: 1
  EPOCHS: 10
  UPDATE_SIZE: 7761
  BATCH_SIZE: 1
  P: 1.0
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: /srv/share/mirshad7/data/robo-vln/trajectory_dir/robo_complete/trajectories.lmdb


MODEL:
  INSTRUCTION_ENCODER:
    use_pretrained_embeddings: False
    is_bert: True