BASE_TASK_CONFIG_PATH: habitat_extensions/config/robo_vlnce_task.yaml
SIMULATOR_GPU_ID: [0]
TORCH_GPU_ID: 0
NUM_PROCESSES: 1
TRAINER_NAME : "robo_vln_trainer"

TENSORBOARD_DIR: /srv/share/mirshad7/data/robo-vln/tensorboard_dirs/seq2seq_bert_complete
CHECKPOINT_FOLDER: /srv/share/mirshad7/data/robo-vln/checkpoints/seq2seq_bert_complete
EVAL_CKPT_PATH_DIR: /srv/share/mirshad7/data/robo-vln/checkpoints/seq2seq_bert_complete

VIDEO_DIR: "videos/debug/seq2seq_text_attn/test/seen"
PLOT_ATTENTION: True
VIDEO_OPTION: []  # options: "disk", "tensorboard"

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_seen
  EPISODE_COUNT: 20
  VAL_LOG_DIR : validation_logging/seq2seq_text_attn/test_run/seen
DAGGER:
  ITERATIONS: 1
  EPOCHS: 10
  UPDATE_SIZE: 570
  #7739  
  #570
  COLLECT_DATA_SPLIT: val_seen
  BATCH_SIZE: 1
  P: 1.0
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: /srv/share3/mirshad7/data/robo-vln/trajectory_dir/robo_complete/val_seen/trajectories.lmdb

MODEL:
  LANG_ATTN:
    use: False
  INSTRUCTION_ENCODER:
    final_state_only: True
    use_pretrained_embeddings: False
    is_bert: True