BASE_TASK_CONFIG_PATH: habitat_extensions/config/robo_vlnce_task.yaml
SIMULATOR_GPU_ID: [0]
TORCH_GPU_ID: 0
NUM_PROCESSES: 1

TENSORBOARD_DIR:  /home/mirshad7/data/tensorboard_dirs/seq2seq/run_2
CHECKPOINT_FOLDER:  /home/mirshad7/data/checkpoints/seq2seq/run_2
EVAL_CKPT_PATH_DIR:  /home/mirshad7/data/checkpoints/seq2seq/run_2/ckpt.9.pth

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 50000
  VAL_LOG_DIR : validation_logging/seq2seq/run_2

DAGGER:
  ITERATIONS: 1
  EPOCHS: 20
  UPDATE_SIZE: 20
  BATCH_SIZE: 1
  P: 1.0
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: /home/mirshad7/data/trajectory_dir/seq2seq/trajectories.lmdb
