BASE_TASK_CONFIG_PATH: habitat_extensions/config/robo_vln_task.yaml
SIMULATOR_GPU_ID: [0]
TORCH_GPU_ID: 0
NUM_PROCESSES: 1
EVAL:
    SPLIT: val_unseen
    # any num greater than the actual episode count evals every episode
    EPISODE_COUNT: 15
    EVAL_NONLEARNING: True
    NONLEARNING:
        # RandomAgent or HandcraftedAgent
        AGENT: RandomAgent
