BASE_TASK_CONFIG_PATH: habitat_extensions/config/robo_vln_task.yaml
SIMULATOR_GPU_ID: [0]
TORCH_GPU_ID: 0
NUM_PROCESSES: 1
TRAINER_NAME : "robo_vln_trainer"

TENSORBOARD_DIR: data/robo-vln/tensorboard_dirs/cma
CHECKPOINT_FOLDER: data/robo-vln/checkpoints/cma
EVAL_CKPT_PATH_DIR: data/robo-vln/checkpoints/cma/ckpt.32.pth 

VIDEO_DIR: ""
PLOT_ATTENTION: False
VIDEO_OPTION: []  # options: "disk", "tensorboard"

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 1224
  VAL_LOG_DIR : validation_logging/cma
DAGGER:
  ITERATIONS: 1
  EPOCHS: 25
  UPDATE_SIZE: 7739
  #7739  
  #570
  #1224
  COLLECT_DATA_SPLIT: train
  BATCH_SIZE: 1
  P: 1.0
  PRELOAD_LMDB_FEATURES: True
  LMDB_FEATURES_DIR: data/trajectories_dirs/robo-vln/train/trajectories.lmdb
  LMDB_EVAL_DIR: data/trajectories_dirs/robo-vln/val_seen/trajectories.lmdb

MODEL:
  INSTRUCTION_ENCODER:
    bidirectional: True
  CMA:
    use: True
  INSTRUCTION_ENCODER:
    use_pretrained_embeddings: True
    is_bert: False