BASE_TASK_CONFIG_PATH: habitat_extensions/config/robo_vln_task.yaml
SIMULATOR_GPU_ID: [0]
TORCH_GPU_ID: 0
NUM_PROCESSES: 1
TRAINER_NAME : "hierarchical_trainer"

TENSORBOARD_DIR: data/robo-vln/checkpoints/tensorboard_dirs/hierarchical_cma
CHECKPOINT_FOLDER: data/robo-vln/checkpoints/hierarchical_cma/
EVAL_CKPT_PATH_DIR: data/robo-vln/checkpoints/hierarchical_cma/

VIDEO_DIR: ""
PLOT_ATTENTION: False
VIDEO_OPTION: []  # options: "disk", "tensorboard"

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 1224
  VAL_LOG_DIR : validation_logging/hierarchical_cma
DAGGER:
  ITERATIONS: 1
  EPOCHS: 45
  UPDATE_SIZE: 20
  BATCH_SIZE: 1
  P: 1.0
  PRELOAD_LMDB_FEATURES: True
  LMDB_FEATURES_DIR: data/trajectories_dirs/robo-vln/train/trajectories.lmdb
  LMDB_EVAL_DIR: data/trajectories_dirs/robo-vln/val_seen/trajectories.lmdb

MODEL:
  INSTRUCTION_ENCODER:
    final_state_only: False
    use_pretrained_embeddings: False
    is_bert: True
