BASE_TASK_CONFIG_PATH: habitat_extensions/config/robo_vln_task.yaml
SIMULATOR_GPU_ID: [0]
TORCH_GPU_ID: 0
NUM_PROCESSES: 1
TRAINER_NAME : "robo_vln_trainer"

TENSORBOARD_DIR: data/robo-vln/tensorboard_dirs/
CHECKPOINT_FOLDER: data/robo-vln/checkpoints/
EVAL_CKPT_PATH_DIR: data/robo-vln/checkpoints/

VIDEO_DIR: ""
PLOT_ATTENTION: False
VIDEO_OPTION: []  # options: "disk", "tensorboard"

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_seen
  EPISODE_COUNT: 570
  VAL_LOG_DIR : validation_logging/
DAGGER:
  ITERATIONS: 1
  EPOCHS: 25
  # UPDATE_SIZE: 7739
  UPDATE_SIZE: 2
  COLLECT_DATA_SPLIT: val_seen
  BATCH_SIZE: 1
  P: 1.0
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: data/trajectories_dirs/robo-vln/val_seen/trajectories.lmdb

MODEL:
  INSTRUCTION_ENCODER:
    is_bert: True