BASE_TASK_CONFIG_PATH: habitat_extensions/config/robo_vlnce_task.yaml
SIMULATOR_GPU_ID: [0]
TORCH_GPU_ID: 0
NUM_PROCESSES: 1
EVAL:
    SPLIT: val_seen
    # any num greater than the actual episode count evals every episode
    EPISODE_COUNT: 570
    EVAL_NONLEARNING: True
    NONLEARNING:
        # RandomAgent or HandcraftedAgent
        AGENT: RandomAgent
